name: Release

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: 'the type of release'
        required: true
        default: 'patch'
        type: choice
        options:
          - 'patch'
          - 'minor'
          - 'major'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: bash script
        run: |
          pip install toml-cli
          

      - name: Extract current version
        id: extract-current-version
        run: |
              version=$(toml get --toml-path pyproject.toml project.version)
              echo "current version: $version"
              echo "release type: ${{ github.event.inputs.release_type }}"
              IFS='.' read -r major minor patch <<< "$version"
              if [ "${{ github.event.inputs.release_type }}" == "patch" ]; then
                echo "current-version=$major.$minor.$patch" >> $GITHUB_OUTPUT
              elif [ "${{ github.event.inputs.release_type }}" == "minor" ]; then
                minor=$((minor+1))
                patch=0
                echo "current-version=$major.$minor.$patch" >> $GITHUB_OUTPUT
              else
                major=$((major+1))
                minor=0
                patch=0
                echo "current-version=$major.$minor.$patch" >> $GITHUB_OUTPUT
              fi
              patch=$((patch+1))
              echo "new-version=$major.$minor.$patch" >> $GITHUB_OUTPUT
              echo "new version: $major.$minor.$patch"

      - name: GH Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.extract-current-version.outputs.current-version }}

      - name: Bump up version
        run: |
          toml get --toml-path pyproject.toml project.version "${{ steps.extract-current-version.outputs.new-version }}\" 
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "bump up version"
          git push
